export const CREATE_ROOM_TOGGLE_POPUP = "CREATE_ROOM_TOGGLE_POPUP";
export const SHOW_PROFILE = "SHOW_PROFILE";
export const SHOW_ROOM_LIST = "SHOW_ROOM_LIST";
export const ROOM_LIST_IS_LOADING = "ROOM_LIST_IS_LOADING";
